# Generated by Django 2.2.6 on 2019-10-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(db_column='comp_name', max_length=264)),
                ('comp_house_count', models.IntegerField(db_column='comp_house_count')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_addr', models.CharField(db_column='House_addr', max_length=264)),
                ('geo_lat', models.FloatField(db_column='geo_lat')),
                ('geo_lon', models.FloatField(db_column='geo_lon')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTwo.Company')),
            ],
        ),
    ]
