# Generated by Django 2.2.6 on 2019-10-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_company_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='comp',
            new_name='comp_id',
        ),
    ]
